---
# Variables here are applicable to all host groups
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
fetch_log_dir: "{{ playbook_dir }}/fetch_logfile"

# default configuration for multiple host groups and roles
node_exporter_port: 9100

# docker
docker_bin_dir: "/usr/bin"

# Adjust time server
# time_server: pool.ntp.org

# Random shifts for retrying failed ops like downloading
retry_stagger: 5
