---

pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"
pump_log_dir: "{{ deploy_dir }}/log"
pump_cert_dir: "{{ deploy_dir }}/conf/ssl"

# systemd: Specifies when to restart the service.
Restart: on-failure
