---
dummy:

tidb_port: 4000
tidb_status_port: 10080

tidb_log_dir: "{{ deploy_dir }}/log"

pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"

# pump binlog to pump sock
pump_socket: "{{ status_dir }}/pump.sock"


tidb_check_alive_user: "root"
tidb_check_alive_password: ""
