---
dummy:

tidb_port: 4000
tidb_status_port: 10080

tidb_log_dir: "{{ deploy_dir }}/log"
tidb_cert_dir: "{{ deploy_dir }}/conf/ssl"

pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"

# pump binlog to pump sock
pump_socket: "{{ status_dir }}/pump.sock"
