---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ mysql_alive_log_dir }}"

- name: deploy mysql_alive binary
  copy: src="{{ resources_dir }}/bin/mysql-alive" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include: "{{ process_supervision }}_deployment.yml"

