---

# default configuration for node_exporter

node_exporter_port: 9100

node_exporter_log_level: info
node_exporter_log_dir: "{{ deploy_dir }}/log"
node_exporter_log_filename: "node_exporter.log"

node_exporter_status_dir: "{{ status_dir }}/node_exporter"