- name: create systemd service configuration
  template: src="systemd_{{ deployment_method }}.service.j2" dest="/etc/systemd/system/{{ service_name }}.service" mode=0644

- name: create startup script - common start/stop
  template:
    src: "{{ item }}_role.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ this_role_name }}.sh"
    mode: "0755"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  with_items:
    - start
    - stop

- name: reload systemd
  shell: "systemctl daemon-reload"
