---

pump_port: 8250

pump_socket: "{{ status_dir }}/pump.sock"

pump_log_dir: "{{ deploy_dir }}/log"
pump_log_filename: "pump.log"

pump_data_dir: "{{ deploy_dir }}/data.pump"

pump_status_dir: "{{ status_dir }}/pump"

pump_metric_interval: "2"

