---

- set_fact:
    collector_dir: "{{ hostvars[groups.monitored_servers[0]].deploy_dir }}"
    service_host: "{{ ansible_host }}"

- name: create fetch directory
  delegate_to: localhost
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ fetch_tmp_dir }}/{{ service_host }}"

- name: collect basic system information
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ node_exporter_log_dir }} --alias={{ inventory_hostname }} system --collector"
  become: true

- include_tasks: collect_log.yml

- name: compress collected data
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ node_exporter_log_dir }} --alias={{ inventory_hostname }} archive"
  become: true

- name: fetch host diagnosis tarball with bandwidth limit
  delegate_to: localhost
  shell: "scp -P {{ ansible_port|default(22) }} -l {{ collect_bandwidth_limit|default('10000') }} -o StrictHostKeyChecking=no {{ service_host }}:{{ node_exporter_log_dir }}/{{ inventory_hostname }}.tar.gz {{ fetch_tmp_dir }}/{{ service_host }}/{{ inventory_hostname }}.tar.gz"
  when: enable_bandwidth_limit|default(true)

- name: fetch host diagnosis tarball without bandwidth limit
  fetch:
    src: "{{ node_exporter_log_dir }}/{{ inventory_hostname }}.tar.gz"
    dest: "{{ fetch_tmp_dir }}/{{ service_host }}/{{ inventory_hostname }}.tar.gz"
    flat: yes
  when: not enable_bandwidth_limit|default(true)

- name: remove host system temporary diagnosis tarball
  file:
    path: "{{ node_exporter_log_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ inventory_hostname }}.tar.gz"
  become: true
