## grafana_collector Configuration

[grafana]
# dashboard theme: [dark, light]
theme = "dark"

# timeout and retry interval of query for rendering panel image, unit: second
client-timeout = 300
server-timeout = 300
retry-interval = 10

## PDF template varialbes
[font]
family = "opensans"
ttf = "OpenSans-Regular.ttf"
size = 14

# rectangle in PDF's page
[rect]
# page: A4 size
[rect.page]
width = 595.28
height = 841.89

# grafana panel type: Graph
[rect.graph]
width = 480.0
height = 240.0

# grafana panel type: Singlestat
[rect.singlestat]
width = 300.0
height = 150.0

[position]
# position x of image
x = 50.0
# position y of first image on page
y1 = 80.0
# position y of second image on page
y2 = 350.0
# height of new line
br = 20.0
