---

- name: deploy blackbox_exporter image
  copy: src="{{ downloads_dir }}/blackbox-exporter.tar" dest="{{ deploy_dir }}/images" mode=0755

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_docker.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run

- name: load docker image from archive
  docker_image:
    state: present
    force: yes
    name: prom/blackbox_exporter
    tag: "{{ blackbox_exporter_tag }}"
    load_path: "{{ images_dir }}/blackbox-exporter.tar"

- include_tasks: "{{ process_supervision }}_deployment.yml"
