---

- name: Gen_certs | copy certs generation script
  copy:
    src: "make-ssl-pump.sh"
    dest: "{{ script_dir }}/make-ssl-pump.sh"
    mode: 0700
  run_once: yes
  delegate_to: localhost
  when: gen_certs|default(false)

- name: Gen_certs | run cert generation script
  command: "{{ script_dir }}/make-ssl-pump.sh -d {{ cert_dir }}"
  environment:
    - PATH: "{{ ansible_env.PATH }}:{{ binary_dir }}"
    - CN: "pump-server"
    - PUMP_HOST: "{{ pump_host }}"
    - PUMP_SOCKET: "{{ pump_socket }}"
  delegate_to: localhost
  when: gen_certs|default(false)
