---
# tasks file for tidb

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pump_data_dir }}"
  - "{{ pump_log_dir }}"
  - "{{ deploy_dir }}/status/{{ role_name }}"

- name: deploy pump binary
  copy: src="{{ resources_dir }}/bin/pump" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create scripts
  include_role:
    name: scripts
  vars:
    this_role_name: pump

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- name: create systemd service configuration
  template:
    src: "pump.service.j2"
    dest: "/etc/systemd/system/pump.service"
    mode: 0644
  when: use_systemd
  vars:
    - ansible_become: false
    - ansible_become_user: root

- name: reload systemd
  shell: "systemctl daemon-reload"
  when: use_systemd
  vars:
    - ansible_become: false
    - ansible_become_user: root

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [pump_port ~ '/tcp'] + firewalld_ports }}"
