---

- name: check tikv log directory
  stat: path={{ tikv_log_dir }} get_md5=false get_checksum=false
  register: log_dir_st

- fail:
    msg: "{{ tikv_log_dir }} must exist and is a directory"
  when: log_dir_st.stat.isdir is not defined or log_dir_st.stat.isdir == False

- name: collect tikv log
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ tikv_log_dir }} --alias=tikv_{{ inventory_hostname }} log --dir={{ tikv_log_dir }} --prefix=tikv --retention={{ collect_log_recent_hours | default('2') }}"
