---

- set_fact:
    collector_dir: "{{ hostvars[groups.monitored_servers[0]].deploy_dir }}"
    service_host: "{{ ansible_host }}"

- name: create tikv fetch directory
  delegate_to: localhost
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ fetch_tmp_dir }}/{{ service_host }}"

- include_tasks: collect_log.yml
- include_tasks: collect_config.yml

- name: collect tikv process information
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ tikv_log_dir }} --alias=tikv_{{ inventory_hostname }} system --collector --port {{ tikv_port }}"
  become: true

- name: compress collected data
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ tikv_log_dir }} --alias=tikv_{{ inventory_hostname }} archive"

- name: fetch tikv diagnosis tarball with bandwidth limit
  delegate_to: localhost
  shell: "scp -P {{ ansible_port|default(22) }} -l {{ collect_bandwidth_limit|default('10000') }} -o StrictHostKeyChecking=no {{ service_host }}:{{ tikv_log_dir }}/tikv_{{ inventory_hostname }}.tar.gz {{ fetch_tmp_dir }}/{{ service_host }}/tikv_{{ inventory_hostname }}.tar.gz"
  when: enable_bandwidth_limit|default(true)

- name: fetch tikv diagnosis tarball without bandwidth limit
  fetch:
    src: "{{ tikv_log_dir }}/tikv_{{ inventory_hostname }}.tar.gz"
    dest: "{{ fetch_tmp_dir }}/{{ service_host }}/tikv_{{ inventory_hostname }}.tar.gz"
    flat: yes
  when: not enable_bandwidth_limit|default(true)

- name: remove tikv temporary diagnosis tarball
  file:
    path: "{{ tikv_log_dir }}/{{ item }}"
    state: absent
  with_items:
    - "tikv_{{ inventory_hostname }}.tar.gz"
