# The directory where binaries are stored on Ansible
# # managed systems.
bin_dir: /usr/bin

# The directory where scripts used for bootstrapping CoreOS
# reside.
bootstrap_script_dir: /opt
pypy_version: 5.6.0

# https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.6.0-linux64.tar.bz2
# http://og66pdz33.bkt.clouddn.com/pypy2-v5.6.0-linux64.tar.bz2
pypy_download_url_base: "https://bitbucket.org/pypy/pypy/downloads"
pypy_download_url: "{{ pypy_download_url_base }}/pypy2-v{{ pypy_version }}-linux64.tar.bz2"

pypy_download_url_under_gfw: "http://og66pdz33.bkt.clouddn.com/pypy2-v5.6.0-linux64.tar.bz2"