---

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pushgateway_log_dir }}"

- name: deploy pushgateway binary
  copy: src="{{ resources_dir }}/bin/pushgateway" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include_tasks: "{{ process_supervision }}_deployment.yml"
