# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576: "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000: "1.3m"

readpool:
  storage:

  coprocessor:

server:

storage:

pd:
# This section will be overwritten by command line parameters

metric:
#address: "172.16.30.31:9531"
#interval: "15s"
#job: "tikv"

raftstore:

coprocessor:

rocksdb:
  wal-dir: ""

  defaultcf:
    block-cache-size: "10GB"

  lockcf:
    block-cache-size: "4GB"

  writecf:
    block-cache-size: "4GB"

raftdb:
  defaultcf:
    block-cache-size: "1GB"

security:
  ca-path: ""
  cert-path: ""
  key-path: ""

import:
