---

tidb_port: 4000
tidb_status_port: 10080

# log level: trace, debug, info, warn, error, off.
tidb_log_level: "info"
tidb_log_dir: "{{ deploy_dir }}/log"
tidb_log_filename: "tidb.log"

tidb_metric_interval: "2"
