---

- name: Disk space check - Fail task when disk is full
  shell: df -h . | tail -n1
  register: disk_space_st
  failed_when: " '100%' in disk_space_st.stdout "
  changed_when: false

- name: get facts
  setup:
    gather_subset: hardware

- name: Preflight check - Get hostnames of all nodes in cluster
  set_fact:
    all_hostnames: |-
      [
      {% set all_hosts = groups['monitored_servers']|unique|sort -%}
      {% for host in all_hosts -%}
        {% set hostname = hostvars[host].ansible_hostname -%}
        "{{ hostname }}",
      {% endfor %}
      ]
  run_once: true
  when: ansible_play_hosts | length == groups['monitored_servers'] | length

- name: Preflight check - Does every node in cluster have different hostname
  fail:
    msg: 'hostnames of all nodes in cluster: {{ all_hostnames | to_yaml }}'
  run_once: true
  when:
    - ansible_play_hosts | length == groups['monitored_servers'] | length
    - all_hostnames | unique | length != groups['monitored_servers'] | length

- name: Preflight check - Get NTP service status
  shell: ntpstat | grep -w synchronised | wc -l
  register: ntp_st
  changed_when: false
  when: enable_ntpd

- name: Preflight check - NTP service
  fail:
    msg: "Make sure NTP service is running and ntpstat is synchronised to NTP server. See https://github.com/pingcap/docs/blob/master/dev/how-to/deploy/orchestrated/ansible.md#how-to-check-whether-the-ntp-service-is-normal ."
  when:
    - enable_ntpd
    - ntp_st.stdout|int != 1

- name: Preflight check - Get umask
  shell: umask
  register: umask
  changed_when: False

- name: Preflight check - Does the system have a standard umask
  fail:
    msg: 'The umask of the system ({{ umask.stdout.strip() }}) prevents successful installation. We suggest a standard umask such as 0022.'
  when: umask.stdout.strip()[-2:] not in ('00', '02', '20', '22')

- name: Preflight check - Get maximum number of open file descriptors limit
  shell: ulimit -H -n
  register: ulimit
  changed_when: False

- name: Preflight check - ulimit -n
  fail:
    msg: 'The default maximum number of open file descriptors is too low {{ ulimit.stdout }}, should be {{ min_open_fds }}'
  when: ulimit.stdout|int < min_open_fds|int

- name: Preflight check - Check swap
  fail:
    msg: "Swap is on, for best performance, turn swap off"
  when: ansible_swaptotal_mb != 0
