groups:
- name: alert.rules
  rules:
  - alert: BINLOG_pump_binlog_count
    expr: rate(binlog_pump_binlog_count[1m]) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: emergency
      expr: rate(binlog_pump_binlog_count[1m]) > 0
    annotations:
      description: 'alert: instance: {{ $labels.instance }} values:{{ $value }}'
      value: '{{ $value }}'
      summary: BINLOG pump binlog count error
      
  - alert: BINLOG_drainer_window_more_than_3600s
    expr: binlog_drainer_window{mark="upper"} - binlog_drainer_window{mark="lower"} > 3600
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: critical
      expr: binlog_drainer_window{mark="upper"} - binlog_drainer_window{mark="lower"} > 3600
    annotations:
      description: 'alert: instance: {{ $labels.instance }} values:{{ $value }}'
      value: '{{ $value }}'
      summary: BINLOG drainer window more than 3600s

  - alert: BINLOG_drainer_error_binlog_count
    expr: rate(binlog_drainer_error_binlog_count[1m]) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: warning
      expr: rate(binlog_drainer_error_binlog_count[1m]) > 0
    annotations:
      description: 'alert: instance: {{ $labels.instance }} values:{{ $value }}'
      value: '{{ $value }}'
      summary: BINLOG drainer error_binlog count

  - alert: BINLOG_drainer_event_error
    expr: sum(rate(binlog_drainer_event[10m])) < 1
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: critical
      expr: sum(rate(binlog_drainer_event[10m])) < 1
    annotations:
      description: 'alert: instance: {{ $labels.instance }} values:{{ $value }}'
      value: '{{ $value }}'
      summary: BINLOG binlog drainer event error

  - alert: BINLOG_drainer_txn_duration_time_more_than_10s
    expr: sum(rate(binlog_drainer_txn_duration_time_bucket[1m])) BY (le, instance) > 10
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: warning
      expr: sum(rate(binlog_drainer_txn_duration_time_bucket[1m])) BY (le, instance) > 10
    annotations:
      description: 'alert: instance: {{ $labels.instance }} values:{{ $value }}'
      value: '{{ $value }}'
      summary: BINLOG binlog drainer txn_duration_time_more_than_10s
