groups:
- name: alert.rules
  rules:
  - alert: disk_used_more_than_90%
    expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 10
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 10
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk used more than 90%
  - alert: disk_used_more_than_90%
    expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 1
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 1
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk used more than 99%
  - alert: disk_readonly
    expr: node_filesystem_readonly{fstype=~"(ext.|xfs)"}  > 1
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: node_filesystem_readonly{fstype=~"(ext.|xfs)"}  > 1
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk readonly
  - alert: disk_inode_more_than_80%
    expr: node_filesystem_files_free{fstype=~"(ext.|xfs)"} / node_filesystem_files{fstype=~"(ext.|xfs)"}  * 100 <= 80
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: node_filesystem_files_free{fstype=~"(ext.|xfs)"} / node_filesystem_files{fstype=~"(ext.|xfs)"}  * 100 <= 80
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk inode more than 80%
  - alert: node_overload
    expr: (node_load5 / count without (cpu, mode) (node_cpu{mode="system"}))  > 1
    for: 5m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: (node_load5 / count without (cpu, mode) (node_cpu{mode="system"}))  > 1
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: node overload
  - alert: cpu_used_more_than_80%
    expr: avg(irate(node_cpu{mode="idle"}[5m])) by(instance) * 100 <= 20
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: avg(irate(node_cpu{mode="idle"}[5m])) by(instance) * 100 <= 20
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: cpu used more than 80%
  - alert: memory_used_more_than_80%
    expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) >= 80
    for: 10m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) >= 80
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: memory used more than 80%
  - alert: tcp_estab_num_more_than_100000
    expr: node_netstat_Tcp_CurrEstab > 100000
    for: 5m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: node_netstat_Tcp_CurrEstab > 100000
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: tcp_estab_num_more_than_100000
  - alert: disk_read_latency_more_than_1s
    expr: rate(node_disk_read_time_ms[5m])/1000 or irate(node_disk_read_time_ms[5m])/1000  > 1
    for: 5m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: rate(node_disk_read_time_ms[5m])/1000 or irate(node_disk_read_time_ms[5m])/1000  > 1
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk_read_latency_more_than_1s
  - alert: disk_write_latency_more_than_1s
    expr: rate(node_disk_write_time_ms[5m])/1000 or irate(node_disk_write_time_ms[5m])/1000  > 1
    for: 5m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: rate(node_disk_write_time_ms[5m])/1000 or irate(node_disk_write_time_ms[5m])/1000  > 1
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: disk_write_latency_more_than_1s
