groups:
- name: alert.rules
  rules:
  - alert: memery_abnormal
    expr: go_memstats_heap_inuse_bytes{job="tidb"} > 1e+09
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: go_memstats_heap_inuse_bytes{job="tidb"} > 1e+09
    annotations:
      description: 'alert: {{ $labels.expr }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiDB mem heap is over 1GiB

  - alert: TiDB_query_duration
    expr: histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) BY (le, instance)) > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) BY (le, instance)) > 1
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB query duration 99th percentile is above 1s

  - alert: TiDB_schema_error
    expr: increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB schema error

  - alert: TiDB_event_error
    expr: increase(tidb_server_server_event{type=~"server_start|server_hang"}[15m])  > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tidb_server_server_event{type=~"server_start|server_hang"}[15m])  > 0
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB event error

  - alert: TiDB_tikvclient_backoff_count
    expr: increase( tidb_tikvclient_backoff_count[10m] )  > 10
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase( tidb_tikvclient_backoff_count[10m] )  > 10
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB tikvclient_backoff_count error

  - alert: TiDB_tikvclient_region_err_total
    expr: increase( tidb_tikvclient_region_err_total[10m] )  > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase( tidb_tikvclient_region_err_total[10m] )  > 1
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB tikvclient_backoff_count error

  - alert: TiDB_domain_load_schema_total
    expr: increase( tidb_domain_load_schema_total{type="failed"}[10m] )  > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase( tidb_domain_load_schema_total{type="failed"}[10m] )  > 1
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB domain_load_schema_total error

  - alert: TiDB_domain_load_schema_total
    expr: increase( tidb_domain_load_schema_total{type="failed"}[10m] )  > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase( tidb_domain_load_schema_total{type="failed"}[10m] )  > 1
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB domain_load_schema_total error

  - alert: TiDB_monitor_keep_alive
    expr: increase(tidb_monitor_keep_alive_total[1m]) < 5
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tidb_monitor_keep_alive_total[1m]) < 5
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB monitor_keep_alive error

  - alert: TiDB_monitor_time_jump_back_error
    expr: increase(tidb_monitor_time_jump_back_total[10m])  > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tidb_monitor_time_jump_back_total[10m])  > 0
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB monitor time_jump_back error
      
  - alert: TiDB_ddl_waiting_jobs
    expr: increase(tidb_ddl_waiting_jobs[10m])  > 5
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tidb_ddl_waiting_jobs[10m])  > 5
    annotations:
      description: 'instance: {{ $labels.instance }} values: {{ $value }} alert: {{ $labels.expr }}'
      value: '{{ $value }}'
      summary: TiDB ddl waiting_jobs too much




  - alert: load_schema_fail
    expr: rate(tidb_domain_load_schema_total{type="failed"}[1m]) > 0
    for: 1s
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: rate(tidb_domain_load_schema_total{type="failed"}[1m]) > 0
    annotations:
      description: 'alert:{{ $labels.expr }} instance:
        {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiDB load schema fails
  - alert: local_shema_latency
    expr: histogram_quantile(1, rate(tidb_domain_load_schema_duration_bucket[5m])) > 5
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: histogram_quantile(1, rate(tidb_domain_load_schema_duration_bucket[5m])) > 5
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiDB load schema latency is over 5s

  - alert: tidb_tikvclient_region_err
    expr: sum(rate(tidb_tikvclient_region_err_total{type="server_is_busy"}[1m])) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tidb_tikvclient_region_err_total{type="server_is_busy"}[1m])) > 0
    annotations:
      description: 'alert: {{ $labels.expr }}
        instance: {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiDB server is busy
