groups:
- name: alert.rules
  rules:
  - alert: TiKV_raft_process_ready
    expr: sum(rate(tikv_raftstore_raft_process_nanos_total{type="ready"}[1m])) BY
      (type, instance) / 1e+09 > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: sum(rate(tikv_raftstore_raft_process_nanos_total{type="ready"}[1m])) BY
        (type, instance) / 1e+09 > 1
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV raft process ready duration is above 1s

  - alert: TiKV_leader_drops
    expr: delta(tikv_pd_heartbeat_tick_total{type="leader"}[30s]) < -10
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr: delta(tikv_pd_heartbeat_tick_total{type="leader"}[30s]) < -10
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}   values:{{ $value }}'
      value: '{{ $value }}'
      summary: TiKV leader drops

  - alert: TiKV_thread_cpu_seconds_total
    expr: sum(rate(tikv_thread_cpu_seconds_total{name=~"raftstore_.*"}[1m])) by (job, name)  > 0.8
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tikv_thread_cpu_seconds_total{name=~"raftstore_.*"}[1m])) by (job, name)  > 0.8
    annotations:
      description: 'alert: {{ $labels.expr }} instance {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV raftstore thread CPU seconds is high

  - alert: TiKV_raft_log_lag
    expr: histogram_quantile(0.99, sum(rate(tikv_raftstore_log_lag_bucket[1m])) by (le, instance, job))  > 5000
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_raftstore_log_lag_bucket[1m])) by (le, instance, job))  > 5000
    annotations:
      description: 'alert: {{ $labels.expr }} instance {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV raftstore log lag more than 5000

  - alert: TiKV_raft_process_duration_secs
    expr: histogram_quantile(0.999, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{type='ready'}[1m])) by (le, instance, job,type)) > 2
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.999, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{type='ready'}[1m])) by (le, instance, job,type)) > 2
    annotations:
      description: 'alert: {{ $labels.expr }} instance {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV raftstore process duration secs more than 2s

  - alert: TiKV_raft_write_log_duration_secs
    expr: histogram_quantile(0.99, sum(rate(tikv_raftstore_append_log_duration_seconds_bucket[1m])) by (le, instance, job)) > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_raftstore_append_log_duration_seconds_bucket[1m])) by (le, instance, job)) > 1
    annotations:
      description: 'alert: {{ $labels.expr }} instance {{ $labels.instance }} values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV raftstore write log druation seconds more than 1s

  - alert: TiKV_channel_full_total
    expr: sum(rate(tikv_channel_full_total[1m])) BY (type, instance) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tikv_channel_full_total[1m])) BY (type, instance) > 0
    annotations:
      description: 'alert: {{ $labels.expr }}  instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV channel full

  - alert: TiKV_async_request_snapshot_duration_seconds
    expr: histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{type="snapshot"}[1m])) by (le, instance, job,type)) > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{type="snapshot"}[1m])) by (le, instance, job,type)) > 1
    annotations:
      description: 'alert: {{ $labels.expr }}  instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV async request snapshot duration seconds more than 1s

  - alert: TiKV_async_request_write_duration_seconds
    expr: histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{type="write"}[1m])) by (le, instance, job,type)) > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{type="write"}[1m])) by (le, instance, job,type)) > 1
    annotations:
      description: 'alert: {{ $labels.expr }}  instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV async request write duration seconds more than 1s

  - alert: TiKV_scheduler_context_total
    expr: abs(delta( tikv_scheduler_contex_total[5m])) > 1000
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  abs(delta( tikv_scheduler_contex_total[5m])) > 1000
    annotations:
      description: 'alert: {{ $labels.expr }} instance:
        {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV scheduler context total

  - alert: TiKV_scheduler_command_duration_seconds
    expr: histogram_quantile(0.99, sum(rate(tikv_scheduler_command_duration_seconds_bucket[1m])) by (le, instance, job,type)  / 1000)  > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_scheduler_command_duration_seconds_bucket[1m])) by (le, instance, job,type)  / 1000)  > 1
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV scheduler command duration seconds more than 1s

  - alert: TiKV_scheduler_latch_wait_duration_seconds
    expr: histogram_quantile(0.99, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket[1m])) by (le, instance, job,type))  > 1
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.99, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket[1m])) by (le, instance, job,type))  > 1
    annotations:
      description: 'alert: {{ $labels.expr }} instance:
        {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV scheduler latch wait duration seconds more than 1s

  - alert: TiKV_thread_storage_scheduler_cpu_seconds
    expr: sum(rate(tikv_thread_cpu_seconds_total{name=~"storage_schedul.*"}[1m])) by (job) > 0.8
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tikv_thread_cpu_seconds_total{name=~"storage_schedul.*"}[1m])) by (job) > 0.8
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV storage scheduler cpu seconds more than 80%

  - alert: TiKV_coprocessor_outdated_request_wait_seconds
    expr: tikv_coprocessor_outdated_request_wait_seconds_count > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  tikv_coprocessor_outdated_request_wait_seconds_count > 0
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV coprocessor outdated request wait seconds

  - alert: TiKV_coprocessor_request_wait_seconds
    expr: histogram_quantile(0.9999, sum(rate(tikv_coprocessor_request_wait_seconds_bucket[1m])) by (le, instance, job,req)) > 10
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  histogram_quantile(0.9999, sum(rate(tikv_coprocessor_request_wait_seconds_bucket[1m])) by (le, instance, job,req)) > 10
    annotations:
      description: 'alert: {{ $labels.expr }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV coprocessor request wait seconds more than 10s

  - alert: TiKV_coprocessor_pending_request
    expr: delta( tikv_coprocessor_pending_request[10m]) > 5000
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  delta( tikv_coprocessor_pending_request[10m]) > 5000
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{
        $value }}'
      value: '{{ $value }}'
      summary: TiKV pending {{ $labels.type }} request is high

  - alert: TiKV_batch_request_snapshot_nums
    expr: sum(rate(tikv_thread_cpu_seconds_total{name=~"endpoint.*"}[1m])) by (job) / ( count(tikv_thread_cpu_seconds_total{name=~"endpoint.*"}) *  0.9 ) / count(count(tikv_thread_cpu_seconds_total) by (instance))
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tikv_thread_cpu_seconds_total{name=~"endpoint.*"}[1m])) by (job) / ( count(tikv_thread_cpu_seconds_total{name=~"endpoint.*"}) *  0.9 ) / count(count(tikv_thread_cpu_seconds_total) by (instance))
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV batch request snapshot nums is high

  - alert: TiKV_thread_apply_worker_cpu_seconds
    expr: sum(rate(tikv_thread_cpu_seconds_total{name="apply_worker"}[1m])) by (job) > 0.9
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(rate(tikv_thread_cpu_seconds_total{name="apply_worker"}[1m])) by (job) > 0.9
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV thread apply worker cpu seconds is high

  - alert: TiKV_write_stall
    expr: delta( tikv_engine_write_stall[10m])  > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  delta( tikv_engine_write_stall[10m])  > 0
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV write stall

  - alert: TiKV_pending_task
    expr: sum(tikv_worker_pending_task_total) BY (job,instance,name)  > 1000
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  sum(tikv_worker_pending_task_total) BY (job,instance,name)  > 1000
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV pending task too much

  - alert: TiKV_coprocessor_request_error
    expr: increase(tikv_coprocessor_request_error[10m]) > 100
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: 1
      expr:  increase(tikv_coprocessor_request_error[10m]) > 100
    annotations:
      description: 'alert: {{ $labels.expr }} type: {{ $labels.type }} instance: {{ $labels.instance }}  values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV coprocessor_request_error 
