---

- name: deploy prometheus binary
  copy: src="{{ resources_dir }}/bin/prometheus" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include_tasks: "{{ process_supervision }}_deployment.yml"
