---

grafana_port: 3000

grafana_log_dir: "{{ deploy_dir }}/log"
grafana_log_filename: "grafana.log"

grafana_data_dir: "{{ deploy_dir }}/data.grafana"

grafana_dashboards_dir: "{{ deploy_dir }}/opt/grafana/dashboards"

grafana_plugins_dir: "{{ deploy_dir }}/opt/grafana/plugins"

grafana_admin_user: "admin"
grafana_admin_password: "admin"

grafana_exec_vars_only: false

grafana_version: 4.1.2
grafana_download_url: "https://grafanarel.s3.amazonaws.com/builds/grafana-4.1.2-1486989747.linux-x64.tar.gz"
