---

grafana_log_dir: "{{ deploy_dir }}/log"
grafana_log_filename: "grafana.log"

grafana_data_dir: "{{ deploy_dir }}/data.grafana"

grafana_dashboards_dir: "{{ deploy_dir }}/opt/grafana/dashboards"

grafana_plugins_dir: "{{ deploy_dir }}/opt/grafana/plugins"

grafana_admin_user: "admin"
grafana_admin_password: "admin"

grafana_api_keys:
 - name: "grafana_apikey"
   role: "Admin"

grafana_exec_vars_only: false

grafana_version: 4.6.3

# docker settings
grafana_tag: 4.6.3
