---
- name: check pd config path
  set_fact:
    pd_conf_dir: "{{ deploy_dir }}/conf"
  when: pd_conf_dir is undefined

- name: check pd config directory
  stat: path={{ pd_conf_dir }} get_md5=false get_checksum=false
  register: conf_dir_st

- fail:
    msg: "{{ pd_conf_dir }} must exist and is a directory"
  when: conf_dir_st.stat.isdir is not defined or conf_dir_st.stat.isdir == False

- name: collect pd config
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ pd_log_dir }} --alias=pd_{{ inventory_hostname }} config --dir={{ pd_conf_dir }} --prefix=pd"
