---

- name: deploy binary
  copy: src="{{ resources_dir }}/bin/tikv-server" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: tikv_binary

- name: backup binary file
  command: mv "{{ tikv_binary.backup_file }}" "{{ backup_dir }}"
  when: tikv_binary.changed and tikv_binary.backup_file is defined

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}
  register: tikv_script

- name: backup script file
  command: mv "{{ tikv_script.backup_file }}" "{{ backup_dir }}"
  when: tikv_script.changed and tikv_script.backup_file is defined

- include_tasks: "{{ process_supervision }}_deployment.yml"
