---

# default configuration for prometheus

# web port / metric port
prometheus_port: 9090

prometheus_log_level: info

prometheus_data_dir: "{{ deploy_dir }}/data.metrics"

prometheus_log_dir: "{{ deploy_dir }}/log"
prometheus_log_filename: "prometheus.log"

prometheus_extra_labels:
  - { label: "monitor", value: "prometheus" }

alert_label: "promethues"

monitoring_group_name: "evaluation"

prometheus_status_dir: "{{ status_dir }}/prometheus"