kube_master_insecure_port: 8080

admission_controllers: NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota

kube_apiserver_bind_address: "0.0.0.0"
 # change to 127.0.0.1 limit local access
kube_apiserver_insecure_bind_address: "0.0.0.0"

services_enabled: true
apiserver_modified: false
controller_manager_modified: false
scheduler_modified: false
kubelet_modified: false

# List of Kubernetes binaries to install.
kube_master_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl
